
name: Github Pages build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build site manually'
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout site
        uses: actions/checkout@v2

      - name: Checkout Ambergen
        uses: actions/checkout@v2
        with:
          repository: kaadmy/ambergen
          path: _ambergen

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build site
        run: python _ambergen/ambergen

      - name: Publish site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
